# Generated by Django 4.1.4 on 2022-12-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_type', '0001_initial'),
        ('supers', '0002_supers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_type.supertype'),
            preserve_default=False,
        ),
    ]
